<?php
namespace app\models;

use yii\mongodb\ActiveRecord;
use DateTime;
use DateTimeZone;

/**
 *
 * @property int $_id
 * @property int $description
 * @property string $created_at
 */
class MongoLog extends ActiveRecord
{

    public function ConllectionName()
    {
        return ['corapi'];
    }

    public function attributes()
    {
        return[
            '_id',
            'description',
            'created_at',
        ];
    }


    public function beforeSave($insert)
    {
        if($this->isNewRecord)
        {
            $dt = new DateTime(date('Y-m-d H:i:s'), new DateTimeZone('UTC'));
            $ts = $dt->getTimestamp();
            $this->created_at =$ts;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }



    public function rules()
    {
        return [
            [[ '_id', 'description', 'created_at'],'safe']

        ];
    }

    public function afterFind()
    {
        if (!empty($this->created_at))
        {


            $dt = new DateTime("", new DateTimeZone('UTC'));
            $dt->setTimestamp($this->created_at);
            $this->created_at = $dt->format('Y-m-d H:i:s');
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}